### ISSUE TITLE
Make `Expr.hashCode` follow `Expr.equals`

### ISSUE THREAD

**Issue by umazalakain** [rise-lang/shine#104]
`Expr.hashCode` tests for syntactic equality, while `Expr.equals` tests for alpha-equivalence. Discriminating by `Expr.hashCode` is only ever used to then discriminate by `Expr.equals`, the former should be more liberal.
A more comprehensive solution is discussed in #77.

**Comment by Bastacyclop** [comment]
I have a naive implementation here:
https://github.com/rise-lang/shine/blob/46dcba15e4fba8bb3ef92b0ebce2a2c775471f73/src/test/scala/apps/separableConvolution2DEqsat.scala#L32-L52

**Comment by umazalakain** [comment]
Should we not always multiply by (small) prime numbers, so that things cannot be factored out? Would it make sense to make this the default implementation of `hashCode`, since keeping `hashCode` as it is without a corresponding `equals` breaks things anyway?

**Comment by Bastacyclop** [comment]
It probably makes sense to use prime numbers yes, I simply wanted a valid implementation and this is not necessarily a good/efficient hashing function. I am in favor or making this the default `hashCode` implementation, we should probably also change the `hashCode` for types in a similar way.

**Comment by umazalakain** [comment]
Closed by #113
