### ISSUE TITLE
DPIA Macro replacement

### ISSUE THREAD

**Issue by michel-steuwer** [rise-lang/shine#139]
#127 replaces the RISE `@primitive` macro and instead generates Scala code at Scala compilation time.

This has a number of advantages:
 - no wired macro behavior that confuses us and the IDE
 - better documentation of our primitives
 - more flexibility for the future to generate different front- and back-ends for our primitives
 - removing the macros enables a migration path towards Scala 3

For the reasons above, we should do something similar for the DPIA macros: `@expPrimitive`, `@accPrimitive`, and `@comPrimitive`.

Here are some considerations and points that we have to address for this.

**Syntax for DPIA primitives**
In #127 we have developed a parser for RISE type schemas. We can reuse parts of this but need to expand it for DPIA.
The syntax implemented in #127 for RISE primitive's is:
```scala
def drop: (n: nat) -> {m: nat} -> {t: data} -> (n+m).t -> m.t
```
For DPIA I suggest the following syntax:
```scala
def drop(n: nat, m: nat, t: data, input: exp[n+m.t, read]): exp[m.t, read]
```

Here are some reasons for this design:
 - In RISE primitives are functions, but not in DPIA, where `drop` represents a fully applied function. The syntax above makes this explicit.
 - By requiring a name for each argument, we don't have to invent names when generating the corresponding class.

We would then generate a class with the following interface from it:
```scala
final case class Drop(n: Nat,
                      m: Nat,
                      dt: DataType,
                      array: Phrase[ExpType]
                     ) extends ExpPrimitive {
  array :: expT((n + m)`.`dt, read)
  override val t: ExpType = expT(m`.`dt, read)

  // ...
}
```

**Translation Boilerplate**
Currently primitives are translated from RISE to via the (massive) `fromRise` function, which internally uses `InferAccessAnnotation`. We should auto-generate this code!

I think that we need to have access to both, the RISE and the DPIA types at the same time to generate this code. Maybe we can create a mapping file that associates the RISE and DPIA primitives (that will be defined in different files). Something like:
```scala
rise.core.primitives.drop => shine.DPIA.primitives.drop
```
We would then parse both definitions to get the types and generate the translation boilerplate code.

**Refactorings**
There are a number of refactorings that would be useful to do for this:

1. factor the `continuationTranslation`, `acceptorTranslation`, `fedeTranslation`, and `streamTranslation` out of the DPIA Primitive classes. This would (as we discussed before) also better follow the functional pattern matching style that we have almost everywhere in the compiler.
2. remove the `eval` function from the DPIA Primitive. Nobody uses it and it is barely implemented for any primitives, so that nobody could use it even if they wanted to.
3. remove the `xmlPrinter`. Nobody uses it anymore.

I would suggest we do 1. before we replace the macros. Otherwise, we will have to integrate these with the generated code somehow. 2. and 3. are a bit orthogonal to this and just cleanups: we can also keep generating code for these.

Opinions @Bastacyclop, @umazalakain, and others?

**Comment by michel-steuwer** [comment]
We should have a look at #20 again, which this would incorporate.

**Comment by Bastacyclop** [comment]
Sounds like a good plan, here are my thoughts.

> For DPIA I suggest the following syntax:
> ```scala
> def drop(n: nat, m: nat, t: data, input: exp[n+m.t, read]): exp[m.t, read]
> ```
> I think that we need to have access to both, the RISE and the DPIA types at the same time to generate this code. Maybe we can create a mapping file that associates the RISE and DPIA primitives (that will be defined in different files)

This sounds reasonable, but could we not have a single primitive definition for both Rise and DPIA when they are common (so I guess for Rise low-level primitives which directly connect to a DPIA functional primitive)? Something like:
```scala
def drop [low-level]: (n: nat) -> {m: nat} -> {t: data} -> (n+m).t [read] -> m.t [read]
```
This saves duplicating things for Rise and DPIA in this case, but also defining the mapping. It might possibly be more confusing when using the definitions as documentation (even though even in Rise we technically need to think about access annotations to write programs that can pass codegen).

Alternatively, we could keep the two separate definitions as you proposed, but we could enforce a convention: two primitives with the same sub-package and name are implicitly mapped to each other (so `forall genpath name: rise.genpath.name => shine.genpath.name`)? The other convention which I think you already need to have in your proposal is that the primtive parameters should be written in the same order.

**Comment by Bastacyclop** [comment]
It might also be worth renaming DPIA packages to follow the same convention as Rise ones as a preparation refactoring step. Before doing this we should try to merge all other pending PRs that would be impacted by this.

**Comment by umazalakain** [comment]
It all sounds really good to me too. Regarding the RISE => DPIA translation, are access annotations the only information that is added in DPIA types? If so, could we just define DPIA primitives and automatically infer back the corresponding RISE primitives?

**Comment by michel-steuwer** [comment]
I think it is important to have two separate definitions for RISE and DPIA primitives.

We have quite a few more primitives in DPIA than in RISE (basically all of the non-expression primitives, e.g. we have a `seq` and `skip` primitive or also `joinAcc` etc).

There could also be primitives that are only in RISE and are completely removed by rewriting before we ever get to DPIA.

I would also like to make the translation between them explicit rather than implicit by some convention. Conventions are harder to understand (specifically if there are some primitives that are not translated as described above). Having a file that makes the mapping explicit doesn't sound too bad to me.

**Comment by michel-steuwer** [comment]
> are access annotations the only information that is added in DPIA types?

Yes they are, but for the reasons above, I would still like to keep the two definitions separated.

**Comment by Bastacyclop** [comment]
> I would also like to make the translation between them explicit rather than implicit by some convention.

Then we might want to consider removing the "primtive parameters should be written in the same order" convention and write something like:
```
rise.core.primitives.drop {m: nat} {t: nat} => Λ(n: Nat) λinput. shine.DPIA.primitives.drop(n, m, t, input)
```

**Comment by Bastacyclop** [comment]
As we discussed today, the main change required to have a generic primitive translation from Rise to DPIA (#20) is to maintain information on the implicit variable subtitutions for primitive type schemes. In other words if a primitive type scheme contains `{n: Nat} -> ..` and `n` is infered to be `1`, we should be able to lookup that `n -> 1` in `fromRise`.

**Comment by michel-steuwer** [comment]
#167 implements support for generating Scala code at Scala compilation time for DPIA primitives.

**Comment by michel-steuwer** [comment]
After the merge of #167 we have now removed all Scala 2 macros. I will, therefore, close this issue.

Work to improve on this will be tracked in #20 and #168
