### ISSUE TITLE
Redefine equality of RISE primitives based on their names

### ISSUE THREAD

**Issue by umazalakain** [rise-lang/shine#141]
Alpha equivalence judges two primitives equal iff they have the same name. The macros for primitive generation however overwrite the `.equals` of primitives and judge two primitives equal if their types are alpha equivalent. We should either remove the `.equals` overwrite and deal with the consequences, or make it compare names in line with what alpha equivalence does.

**Comment by Bastacyclop** [comment]
I don't like comparing names because it is not as efficient and feels like a hack (are we stringly-typed now? ;p).

**Comment by umazalakain** [comment]
Should we have a unique ID for each of the primitives? Comparing their type schemas is not enough, as you could have two different primitives with the same type schema. Comparing types is wrong, since these types can have free variables.

**Comment by michel-steuwer** [comment]
Isn't it enough to compare the Scala types?

**Comment by umazalakain** [comment]
Er, yes, I will make that into a commit
