### ISSUE TITLE
KernelCallCmd's output changes type during visitAndRebuild

### ISSUE THREAD

**Issue by michel-steuwer** [rise-lang/shine#165]
For the `KernelCallCmd` class:
```
case class KernelCallCmd(name: String,
                         localSize: LocalSize,
                         globalSize: GlobalSize,
                         output: Phrase[AccType],
                         args: Seq[Phrase[ExpType]]) extends CommandPrimitive
```
the type of `output` changes between `acc[dt]` and `acc[managed[dt]]`.

Adding either of these assertions to the class body makes them fire:
```
assert(output.t.dataType.isInstanceOf[ManagedBufferType])  // output's type is acc[managed[...]]
assert(!output.t.dataType.isInstanceOf[ManagedBufferType]) // output's type is not acc[managed[...]]
```

**Comment by Bastacyclop** [comment]
This sounds expected to me as transformations in `shine.OpenCL.Compilation.HostManagedBuffers` change `dt` to be `managed[dt]` where necessary:
```scala
  // Given a host program which only operates on plain arrays,
  // this pass inserts host managed buffers where needed,
  // as well as host execution sections where plain arrays can still be used
```
I would say that the visitor which transforms types in this way should be `shine.OpenCL.Compilation.HostManagedBuffers.InsertManagedBuffersVisitor`.

**Comment by michel-steuwer** [comment]
This means that we can not specify the type of `KernelCallCmd`.

Is there a reason why this change is made at the type level (i.e. `acc[dt] -> acc[managed[dt]]`) rather than at the value level (i.e. inserting a `managed` primitive with identify type in front of `output`)?

**Comment by Bastacyclop** [comment]
Maybe the confusion here is because I am using the shortcut where:
```scala
case class KernelCallCmd(name: String,
                         localSize: LocalSize,
                         globalSize: GlobalSize,
                         output: Phrase[AccType],
                         args: Seq[Phrase[ExpType]]) extends CommandPrimitive
```
Might also be modeled in a more streamlined way as (as is done in `KernelCall` and `ForeignFunctionCall`):
```scala
case class KernelCallCmd(name: String,
                         localSize: LocalSize,
                         globalSize: GlobalSize,
                         inTs: Seq[DataType],
                         outT: DataType,
                         output: Phrase[AccType],
                         args: Seq[Phrase[ExpType]]) extends CommandPrimitive {
  (inTs zip args).foreach{
    case (inT, arg) => arg :: expT(inT, read)
  }
  output :: accT(outT)
}
```
This modeling introduces information redundancy but matches more closely what we might write on paper roughly as:
`def kernelCallCmd{name: String, localSize: LocalSize, globalSize: GlobalSize}(inTs: data.., outT: data, output: acc[outT], args: exp[inTs.., read])`?

Otherwise I have no idea what the implications of using a `managed` primitive would be and how it would fit in the current design.

**Comment by michel-steuwer** [comment]
The problem here is that `output :: accT(outT)` is just not true when it sometimes also is `acc[managed[dt]]`.

**Comment by Bastacyclop** [comment]
What is wrong with `outT = managed[dt]`?

**Comment by michel-steuwer** [comment]
However, I write the type of `KernelCallCmd` it is wrong as the type _changes_.

If I write:
```
def kernelCallCmd{name: String,
                  localSize: shine.OpenCL.LocalSize,
                  globalSize: shine.OpenCL.GlobalSize,
                  args: Seq[Phrase[ExpType]]}
                 (dt: data, output: acc[managed[dt]]): comm
```
then the type is wrong _before_ `InsertManagedBuffersVisitor` changes the `output` type from `acc[dt]` to `acc[managed[dt]]`.

If I write:
```
def kernelCallCmd{name: String,
                  localSize: shine.OpenCL.LocalSize,
                  globalSize: shine.OpenCL.GlobalSize,
                  args: Seq[Phrase[ExpType]]}
                 (dt: data, output: acc[dt]): comm
```
then the type is wrong _after_ `InsertManagedBuffersVisitor` changes the type.

Do you see the problem now?

**Comment by Bastacyclop** [comment]
I do not see the problem, but I do see that `InsertManagedBuffersVisitor` would need to be changed with some additional boilerplate, it cannot rely on a trivial `Continue` anymore, but now needs to do something like:
```scala
case ocl.KernelCallCmd(name, ls, gs)(inTs, outT, output, args) =>
  val output2 = visit(output)
  val args2 = args.map(visit)
  Stop(ocl.KernelCallCmd(name, ls, gs)(args2.map(_.dataType), output2.dataType, output2, args2))
```

**Comment by michel-steuwer** [comment]
I guess we will have to talk about this tomorrow morning :-)
