### ISSUE TITLE
Make runtime library (more) platform agnostic

### ISSUE THREAD

**Issue by bpervan** [rise-lang/shine#184]
After discussions with @Bastacyclop and @michel-steuwer, I'm opening this issue to further discuss the reuse of the ```runtime.h``` interface for other hardware devices. The initial idea was to reuse parts of OpenCL host code generation for other targets, but if we are to proceed in such a manner, it would be convenient to rise the level of abstraction of the runtime library making it (more) platform agnostic. I made a proposal + brief implementation for GAP8, diff is here:

[https://github.com/rise-lang/shine/compare/runtime-backend](https://github.com/rise-lang/shine/compare/runtime-backend)

The gist of the proposed changes is to wrap platform differences in generic structures which should be implemented by the concrete platforms, as @Bastacyclop previously did with ```Context```, ```Kernel```, and ```Buffer```. I added ```ContextParams``` (wraps parameters needed for ```Context``` creation), ```KernelParams``` (wraps parameters needed for loading ```Kernel```), and ```LaunchConfig``` which wraps configuration specifics needed for running kernel (i.e. local size and global size for OpenCL targets, or the number of used cores / threads if target platform is GAP8). Actually, when I think of it, anything that is tied to a concrete platform probably shouldn't reside in ```runtime.h```

Comments please :)

**Comment by Bastacyclop** [comment]
@bpervan it would be easier to comment on the code if there was a WIP PR in my opinion.

The idea sounds fine, however in my opinion we only benefit from generic structures if we have generic APIs to handle them:

https://github.com/rise-lang/shine/blob/33e287c5a9d503b2c6245d8832a254eb7b1dd77f/runtime/runtime.h#L31

How do you build `ContextParams` in a generic way? I think that I would simply remove this function from the generic header, then ...

https://github.com/rise-lang/shine/blob/f58db30421c4b769c466135232489120641184ff/runtime/runtime.h#L23

..., backend-specific functions like this one can still be available in specific headers like `ocl.h`.

https://github.com/rise-lang/shine/blob/33e287c5a9d503b2c6245d8832a254eb7b1dd77f/runtime/runtime.h#L41

How do you build `KernelParams` in a generic way? Maybe this should remain a macro like it currently is, with backend-dependent macro expansion?

https://github.com/rise-lang/shine/blob/33e287c5a9d503b2c6245d8832a254eb7b1dd77f/runtime/runtime.h#L49

Here as well, how do you build `LaunchConfig` in a generic way? As a second comment, why not bake the launch config in `const KernelArg* args)`?

----

I worry that if there is no generic way to manipulate these new abstractions, then introducing them will not enable the host code generator to be more generic than before.

----

Smaller comment:

https://github.com/rise-lang/shine/blob/33e287c5a9d503b2c6245d8832a254eb7b1dd77f/runtime/runtime.h#L8-L12

Maybe `runtime.h` should include neither, instead the generated code should include the right backend-specific header?

**Comment by bpervan** [comment]
I might be missing something, but what actually prevents us to differently implement the aforementioned ```ContextParams``` and ```KernelParams``` through respective structures?

GAP8:
```c
struct KernelParamsImpl {
   void (*handler)(void* args);
    size_t stack_size;
}

struct ContextParamsImpl {
    int device_id;
}

struct LaunchConfig {
    size_t num_threads;
}
```

OpenCL:
```c
struct KernelParamsImpl {
    char* name;
    char* source;
}

struct ContextParamsImpl {
    char* platform_subname;
    char* device_type_str;
}

struct LaunchConfig {
    size_t* global_size;
    size_t* local_size;
}
```

As for not baking ```KernelArg``` in ```LaunchConfig```, I was initially thinking that these two differ semantically, but we can rethink this, of course, as we can for the right way to include appropriate header file. Yep, I agree, I should have made this a WIP PR.
