### ISSUE TITLE
[BUG] Compilation of the generated OpenMP code fails (Canonical Loop Form)

### ISSUE THREAD

**Issue by bpervan** [rise-lang/shine#189]
**Describe the bug**
Consider the following expression:
```scala
val simple: ToBeTyped[Rise] = fun((3`.`int) ->: (3`.`int))(in =>
    in |> mapPar(fun(e => add(e)(l(1))))
)
```
which translates to:
```c
void foo(int* output, int* e133){
    #pragma omp parallel for
    for (int i_162 = 0;(i_162 < 3);i_162 = (1 + i_162)) {
        output[i_162] = (e133[i_162] + 1);
    }
}
```
Trying to compile the following snippet yields
```error: invalid controlling predicate```

It seems that the culprit(s) are parentheses around the testing expression, as the generated for loop doesn't conform with the so called [Canonical Loop Form](https://www.openmp.org/spec-html/5.0/openmpsu40.html)

**To Reproduce**
1. Translate an expression with ```mapPar``` primitive using OpenMP generator.
2. Try compiling the snippet by invoking ```gcc -fopenmp -o snippet snippet.c```

**Expected behavior**
The generated block should be compilable by the OpenMP-implementing compiler

**Platform (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04.2]
 - JVM and Scala Version [e.g. JVM 1.8 and Scala 2.13.3]
 - gcc 9.3.0

**Comment by Bastacyclop** [comment]
Duplicate of #17

**Comment by bpervan** [comment]
Indeed
