### ISSUE TITLE
multiple test_util packages

### ISSUE THREAD

**Issue by martin-luecke** [rise-lang/shine#39]
In each of our shine, rise and elevate repositories we have a `test_util` package at the top level. Supposedly this causes confusion in the IntelliJ IDE such that no tests relying on this can be executed. Moving them one level in (ex. `shine.test_util`) should remove the ambiguities.

**Comment by Bastacyclop** [comment]
@martin-luecke @michel-steuwer I think this is fixed? If so, close the issue :)
