### ISSUE TITLE
Reduce boilerplate in definition of fully applied DPIA primitives

### ISSUE THREAD

**Issue by Bastacyclop** [rise-lang/shine#41]
When defining DPIA primitives, we have to define a lot of boilerplate including writing the type of arguments both in scala and in the DPIA world, defining `visitAndRebuild`, `xmlPrinter`, ..
This is especially painful when refactoring (https://github.com/rise-lang/shine/pull/37), dealing with merge conflicts, or when new boilerplate needs to be added. For example, defining a dot printer or other pretty printer as done in rise (@bastianhagedorn, @roger-uw) would require much more boilerplate for DPIA expressions.

We could make this easier by either defining primitives as functions as done in `rise` (which does not prevent us from maintaining a fully applied normal form where practical or even defining convenient extractors), and/or by factorising code, using macros, ..

One old improvement idea was to make traversal more generic than with `visitAndRebuild`.
```scala
abstract class PrimitiveExpr {
  override def children(): List[Node] = [f, init, array]
  override def rebuild(t: Option[Type]): List[Node] => PrimitiveExpr
}
```
Which would basically allow to recover the benefits of defining primitives as functions by having access to the implicit application nodes hidden in our fully applied primitives.

**Comment by michel-steuwer** [comment]
I do not think we want to make primitives functions as in RISE, as this unnecessarily complicates the code generation process (how to we generate code for a partially applied function?)

I would suggest that we should look into using macros to generate the boilerplate for DPIA primitives - as we have done for RISE.

**Comment by Bastacyclop** [comment]
@michel-steuwer should we close this issue now?
