### ISSUE TITLE
RISE Syntax Discussion

### ISSUE THREAD

**Issue by michel-steuwer** [rise-lang/shine#67]
Hi everyone.

At the start let me point to [Wadler's Law](https://wiki.haskell.org/Wadler's_Law) (before the fighting begins ;-)):
```
In any language design, the total time spent discussing
a feature in this list is proportional to two raised to
the power of its position.
	0. Semantics
    1. Syntax
    2. Lexical syntax
    3. Lexical syntax of comments
```

This issue should be a space to discuss syntax for RISE.

I believe we should aim for:
 1. consistency
 2. clarity and closeness to the formal syntax and to existing FP conventions (and yes, there are many to choose from ...) 

Here is a summary of most of the syntax we have currently in RISE.
https://github.com/rise-lang/shine/pull/66 would change some of this syntax (especially `nFunT` to `forallNat`).

Term Syntax
=======
- Lambda:
    - `fun(x => e)`
    - `fun(t)(x => e)`
- DepLambda:
    - `nFun(n => e)` | `nFun(r, n => e)`
    - `dtFun(dt => e)`
- App:
    - `f(e)`
    - `e |> f`
    - `f $ e`
- DepApp:
    - `f(n)` | `f(dt)` | `f(a)` | `f(n2n)` | `f(n2d)`
- Literal:
    - `l(i)` | `l(f)` | `f(d)`
    - `lidx(i, n)`
    - `lvec(v)`
    - `larr(a)`
- Function composition:
    - `f >> g`
    - `g o f`

Type Syntax
===========
- FunType:
    - `t1 ->: t2`
- DepFunType:
    - `nFunT(n => t)`
    - `dtFunT(dt => t)`
    - `aFunT(a => t)`
    - `n2nFunT(n2n => t)`
    - `n2dFunT(n2d => t)`
- Inferred (implicit) type parameter:
    - `implNat(n => t)`
    - `implDt(dt => t)`
    - `implType(ty => t)`
    - `implBT(bt => t)`
    - `implST(st => t)`
    - `implAddr(a => t)`
    - `implN2n(n2n => t)`
    - `implN2DT(n2d => t)`

 DataType Syntax
 ---------------
 - ScalarType:
    - `bool`
    - `int`
    - `i8` | `i16` | `i32` |`i64`
    - `u8` | ...
    - `f16` | ...
- VectorType:
    - `vec(n, dt)`
- PairType:
    - `t1 x t2`
- ArrayType:
    - `n.t`
- DepPairType:
    - `n2dPairT(n => t)`
    - `nats2dPairT(ns => t)`
- DepArrayType:
    - `n..(i => t)`
    - `n..(n2d)`
- NatToDataApply:
    - `n2d(n)`

NatToData Type Syntax
----------------
- NatToDataLambda:
    - `n2dtFun(n => t)` | `n2dtFun(r)(n => t)` | `n2dtFun(u)(n => t)`

NatToNat Type Syntax
----------------
- NatToNatLambda:
    - `n2nFun(n => t)` | `n2nFun(r)(n => t)` | `n2nFun(u)(n => t)`

**Comment by Bastacyclop** [comment]
I think that the `DepArrayType` syntax `..` looks more like a range to me, as in `for i in 0..n`. I would be in favor of overloading the array `.` or finding something else.

**Comment by michel-steuwer** [comment]
The challenge with the `DepArrayType` was to find something that works well on paper and in code.
For clarity, I think the dependent from should be easily distinguishable from the ordinary array type, therefore, overloading the `.` notation should be avoided.
Option on this one, @fedepiz?

**Comment by michel-steuwer** [comment]
For the `DepFunType` types I suggest to unify the syntax following these two principles:
- We try to make it clear if the parameter is implicit (i.e. it will be inferred and can't be given explicitly) or explicit (i.e. it must be given explicitly)
- We try to stay close to the syntax on paper (`(n: nat) -> t`)

I suggest to achieve this with the following syntax:
```scala
impl((n: Nat) => t) // instead of implNat(n => t)
...
expl((n: Nat) => t) // instead of nFunT(n => t), or forallNat(n => t) as suggested in PR 66
...
```

Resulting in primitve definition looking like:
```scala
@primitive object depMapSeq extends Primitive with Builder {
   impl((n: Nat) =>
     impl((ft1: NatToData) => impl((ft2: NatToData) =>
       expl((k: Nat) => ft1(k) ->: ft2(k)) ->: (n`..`ft1) ->: (n`..`ft2))))
 }
```

**Comment by Bastacyclop** [comment]
That seems reasonable to me. Did we not have syntax such as `(n: Nat) ->: t` in DPIA at some point? Not sure if that is practical in scala or not but we could also see:
```scala
impl(n: Nat) ->: t // instead of implNat(n => t)
(n: Nat) ->: t // instead of nFunT(n => t), or forallNat(n => t)
```

**Comment by michel-steuwer** [comment]
In DPIA/Shine we can get closer because we don't use the scoping mechanism of Scala to introduce the variable `n` into scope, but for RISE I don't see how to get closer to the paper notation.

**Comment by Bastacyclop** [comment]
possible variant to reflect `{ n: nat } ->` versus `(n: nat) ->`:
```scala
@primitive object depMapSeq extends Primitive with Builder {
   impl{ n: Nat =>
     impl{ ft1: NatToData => impl{ ft2: NatToData =>
       expl( k: Nat => ft1(k) ->: ft2(k) ) ->: (n`..`ft1) ->: (n`..`ft2) }}}
 }
```

**Comment by michel-steuwer** [comment]
Yes, I agree, but this could only be a convention, as I don't see how we can enforce this syntax.

**Comment by Bastacyclop** [comment]
We might be able to add some scalastyle regex rules to try and ensure things like this?

**Comment by michel-steuwer** [comment]
@Bastacyclop maybe you can have a look into if that's possible.

If we can't enforce it, I would suggest that we stick with the `()` notation.
The `impl` vs. `expl` notation makes it clear what is what.

**Comment by Bastacyclop** [comment]
http://www.scalastyle.org/rules-dev.html#org_scalastyle_file_RegexChecker
https://regexr.com/5cpe2

**Comment by michel-steuwer** [comment]
I have started a branch to implement the changes discussed here: https://github.com/rise-lang/shine/compare/migrate-to-scala-2.13...feature/improve-RISE-syntax

**Comment by michel-steuwer** [comment]
Currently, we use `nFun` and `dtFun` for (what we call) _dependent lambdas_, ie. lambdas that have a [depdent function type](https://en.wikipedia.org/wiki/Dependent_type#%7F'%22%60UNIQ--postMath-00000003-QINU%60%22'%7F_type).

As we can abstract also over:
 - `AddressSpace`
 - `NatToNat` functions
 - `NatToData` functions

it might make sense to extend this notation to also add `aFun` (or `adrFun`), `n2nFun`, and `n2dFun`.

**But** we currently use `n2nFun` and `n2dFun` for the lambda expressions that take
 - a natural number to a natural number, ie., a "_type level_" function of type: `Nat -> Nat`; and
 - a natrual number to a data type, ie., a "_type level_" function of type `Nat -> DataType`

How to we resolve this and find a unified notation that makes the difference clear?
Opinions @Bastacyclop, @bastian-koepcke and @fedepiz?

One possible way would be to use a single `depFun` for the dependen lambdas and mark the argument type (similar to how we now mark the dependent function types using `impl` and `expl` as discussed above).
So this would mean:
 - `nFun(n => expr)` would become `depFun((n: Nat) => expr)`
 - `dtFun(dt => expr)` would become `depFun((dt: DataType) => expr)`
 - we add: `depFun((a: AddressSpace) => expr)`
 - we add: `depFun((n2n: NatToNat) => expr)`
 - we add: `depFun((n2d: NatToData) => expr)`

It means a bit more typing, but I like this, because it emphasises the type of the argument (ie, it is clear that `n2d` is a function itself) and it has a clear commention to the type syntax we use.

We could then keep the `n2nFun` and `n2dFun` for the type level lambdas.

**Comment by Bastacyclop** [comment]
I don't have a strong opinion on this, except that we should avoid the inconsistency you are highlighting.
The extra characters will be slightly annoying for some use cases but this might be mitigated if we can write things like `depFun((n, m, o: Nat) => expr)` and/or  `Λ((n: Nat) => expr)` (although I usually avoid unicode for lack of easy insertion..). Another option would be to use `natParam(n => expr)`, which is less formal but maybe more intuitive.
Otherwise, your proposal is fine by me.

**Comment by michel-steuwer** [comment]
I would also prefer to avoid Unicode characters.
I don't see the consistency of `natParam` with `fun` (even though it clarifies the `nat` is the parameter part).

**Comment by Bastacyclop** [comment]
This is a bit orthogonal, but maybe in the future we can find a better way to write program arguments in general.
Here is an example that could look better:
```scala
  val camera_pipe: Expr = nFun(h => nFun(w => nFun(hm => nFun(wm =>
    fun((2*(h+6)+36)`.`(2*(w+6)+20)`.`u16)(input =>
    fun(hm`.`wm`.`f32)(matrix_3200 =>
    fun(hm`.`wm`.`f32)(matrix_7000 =>
    fun(f32)(color_temp =>
    fun(f32)(gamma =>
    fun(f32)(contrast =>
    fun(int)(blackLevel =>
    fun(int)(whiteLevel =>
    fun(f32 ->: (3`.`(2*h)`.`(2*w)`.`u8))(sharpen_strength => ...
```
Here is a "dream" syntax for me (not considering scala restrictions):
```
program camera_pipe(
  h: Nat, w: Nat,
  wm: Nat, wm: Nat,
  input: (2*(h+6)+36)`.`(2*(w+6)+20)`.`u16,
  matrix_3200: hm`.`wm`.`f32,
  matrix_7000: hm`.`wm`.`f32,
  color_temp: f32,
  contrast: f32,
  blackLevel: int,
  whiteLevel: int,
  sharpen_strength: f32
): (3`.`(2*h)`.`(2*w)`.`u8)) = ...
```

**Comment by michel-steuwer** [comment]
@Bastacyclop I don't see how we could implement this in the Scala DSL, but that should be of interest for the development of a parser.

**Comment by michel-steuwer** [comment]
I suggest to use for the `DepPairType` the following syntax (which follows standard syntax closely):
```Scala
Nat `**` (n => t) // instead of n2dPairT(n => t)
```
and
```Scala
NatCollection `**` (ns => t) // instead of nats2dPairT(ns => t)
```

Opinions @fedepiz?

**Comment by fedepiz** [comment]
I like the `DepPairType` syntax with the `**` very much. Much better than the wordy version.

About the `DepArray` discussion coming down from before, what about a compromise solution and going for `*.` or `.*`? Although this is very weird and a bit of an eyesore, it checks some boxes:
 * It has a `.`, which is the separator from array size/element type
 * It is all ASCII
 * It uses a `*`, which is something in common with the `DepPairType`

Thoughts? @Bastacyclop @michel-steuwer

**Comment by Bastacyclop** [comment]
I think `*.` and `.*` are better than `..`, so it works for me.
But I still think overloading `.` is also a good alternative. After all, this is what you do in the paper notation:
![image](https://user-images.githubusercontent.com/4070553/94530105-87820e80-0232-11eb-9fa3-002c4ecfcf7d.png)

**Comment by michel-steuwer** [comment]
I am fine with `*.`

For the overloading the difference is obvious if the right hand side is a nat to data lambda (like in the figure that btw. doesn't use any of our formal syntax):
```
expl((n: Nat) =>
  n `*.`(i => i`.`f32) )
```

But that is not always the case, as it can also be a type variable as in:
```
expl((n: Nat) => expl((n2d: NatToData) =>
  n`*.`n2d )
```
