### ISSUE TITLE
Traversals should visit Nats inside NatToNat and NatToData.

### ISSUE THREAD

**Issue by Bastacyclop** [rise-lang/shine#75]
Currently, if you define a visitor such as:
```scala
    case class Visitor() extends traversal.Visitor {
      override def visitNat(in: Nat): Result[Nat] =
        Continue(substitute.natInNat(n, `for`, in), this)
    }
```
This will not visit nats inside Nat2Nat or Nat2Data constructs, using the default implementations that skip them:
```scala
    def visitN2N(n2n: NatToNat): Result[NatToNat] = Continue(n2n, this)
    def visitN2D(n2d: NatToData): Result[NatToData] = Continue(n2d, this)
```
This breaks code such as `substitute.natsInType`:
https://github.com/rise-lang/shine/blob/e2e1039bdf4ae98d5af1feb0cfa87d928297ba0b/src/main/scala/rise/core/substitute.scala#L116-L123

To fix this, the contained nats should be visited.

**Comment by Bastacyclop** [comment]
https://github.com/rise-lang/shine/pull/74/ starts to fix this issue

**Comment by Bastacyclop** [comment]
@umazalakain I think that we can close this issue after #98 ?

**Comment by umazalakain** [comment]
Yes!
